### ISSUE TITLE
JAIN SIP stack was re-initialized with every REGISTRATION

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#141]
...and without being shutdown first. I think the proper behaviour is to shutdown and restart stack only when registrar/proxy is updated where the sip stack properties need to be changes (i.e. android.javax.sip.OUTBOUND_PROXY)

**Comment by deruelle** [comment]
You probably don't want to restart the stack at all. You can avoid using that property and just add a new Route Header yourself for every call to the right destination

**Comment by atsakiridis** [comment]
good idea @deruelle. I was searching for a way to modify stack properties but didn't find any hence the proposal. But Route header seems even better :)
