### ISSUE TITLE
When calling 1235 Restcomm application from mobile network, the call is never terminated

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#172]
Scenario:

- Make a call from Messenger to 1235 using Mobile internet
- Calls is answered fine, but after announcement ends no BYE seems to be received from Restcomm

Analysis:

Seems that Restcomm sends the BYE to the wrong ip address i.e. 100.97.128.27 which is the contact used in the INVITE, instead of the ip address from which the INVITE was received i.e. 62.74.11.124. 

I compared this scenario with a wifi scenario and the only difference seems to be that:
- in wifi scenario the 'internal' ip that is used in the contact is 192.168.2.41 (which is a true internal IP)
- in mobile scenario the 'internal' ip that is used in the contact is 100.97.128.27 (which is not really in the internal ip range 10.* or 192.168.*)

So I'm guessing maybe Restcomm decides where to route the BYE based on if the contact ip address is internal or external and hence sends to the wrong destination.

Scenario restcomm logs for mobile: https://gist.github.com/atsakiridis/8eaf982a750991ce894e
Scenario restcomm logs for wifi: https://gist.github.com/atsakiridis/a695594dd291a4811d58

@gvagenas, does this make sense?

**Comment by gvagenas** [comment]
@atsakiridis The 100.97.128.27 is a valid public ip address so Restcomm will use it. The only way that Restcomm can decide if the Contact address will be replaced with the peer address (the one that the message actually received) is by checking if the Contact ip address is a private ip address. 

If Contact ip address is private one, then Restcomm will replace it with the peer address. 
So in the Wifi case, your client gets a private address 192..... but the message arrives to Restcomm from your public ip address (the one that your router gets from your ISP). Next Restcomm will see that 192. is private one and will replace it with the ip of your router.

In your case why the Contact ip address is different than the peer address? Why you have 100.97.128.27 and 62.74.11.124? Why two public ip addresses?

George

**Comment by atsakiridis** [comment]
@gvagenas: I don't  know :( I'm guessing it's how mobile operators handle it? Maybe having 2 layers of public networks for security or something? You know what? Let me try to use a different client from my Android device and compare the IP I see in the device, with the IP I see from Restcomm logs and I'll get back to you

**Comment by atsakiridis** [comment]
@gvagenas: checked with csipsimple and again the 100.* address still seems to be the ultimate originator, even though Restcomm (always on) talks to 62.*, so indeed it seems to be a mobile internet topology of some sort. Also, I noticed that, BYE from Restcomm again times out but this time for a different reason:

CSipSimple seems to be smart enough to change the contact and use 62.* address in the INVITE:

INVITE sip:54.83.196.238:5060 SIP/2.0^M
Via: SIP/2.0/UDP 10.165.137.17:5065;branch=z9hG4bKPjBDZL7oAyBHEpryaJADIzGr9oPP5l1Z7p7LQ2xzsd_0^M
Via: SIP/2.0/UDP 10.165.137.17:5060;branch=z9hG4bKPjBDZL7oAyBHEpryaJADIzGr9oPP5l1Z7p7LQ2x_0^M
Via: SIP/2.0/UDP 62.74.6.49:7094;rport=7094;branch=z9hG4bKPjBDZL7oAyBHEpryaJADIzGr9oPP5l1Z7p;received=62.74.6.49^M
Max-Forwards: 69^M
From: "antonis" <sip:antonis@23.23.228.238>;tag=PJaBb6gtPzYDj.nx8-7Vdjp-nU08udvj^M
To: <sip:1234@23.23.228.238>;tag=48441547_241918b0_57a5b08a_2cd6356a^M
Contact: <sip:antonis@62.74.6.49:7095;ob>^M
Call-ID: 7LQ2xKGJYTjI3dNnT97UlDbcULjMT8rE^M
CSeq: 20788 INVITE^M
Proxy-Authorization: Digest username="antonis",realm="23.23.228.238",nonce="36366164393839622d333434622d343",uri="sip:1234@23.23.228.238",response="24b8d6e025650fc3ae60862f7f84be8c"^M
Allow: PRACK,INVITE,ACK,BYE,CANCEL,UPDATE,INFO,SUBSCRIBE,NOTIFY,REFER,MESSAGE,OPTIONS^M
Supported: replaces,100rel,timer,norefersub^M
Session-Expires: 1800

And the reason BYE fails is that the port used doesn't seem to answer.

Any thoughts on how I could find out which is the external ip/port (i.e. 62.*) without using a STUN server that we could implement a bit later? Any SIP fields that could help? For example I noticed that in the 200 OK to the REGISTER, in the Via there's a received field holding the external ip of Messenger:

SIP/2.0 200 OK^M
To: "antonis-2" <sip:antonis-2@23.23.228.238>;tag=47805000_241918b0_57a5b08a_b5a5ecd1^M
Via: SIP/2.0/UDP 192.168.2.42:5080;rport=5080;branch=z9hG4bK-3234-6e8541f14e80bff6c34b9776b8b7ed73;received=79.167.184.51^M
CSeq: 2 REGISTER^M
Call-ID: 314cd96a419aab4c0c5a92c37181444d@192.168.2.42^M
From: "antonis-2" <sip:antonis-2@23.23.228.238>;tag=c3ff411e^M
Server: TelScale Restcomm 7.3.1.1157^M
Contact: <sip:antonis-2@79.167.184.51:5080;transport=udp;registering_acc=23.23.228.238>;expires=3600^M
Content-Length: 0

Do you believe that would work?

P.S. If you need more info on the CSipSimple session, here are the Restcomm logs: https://gist.github.com/atsakiridis/012715a908992f0094d5

**Comment by gvagenas** [comment]
@atsakiridis, 
I did a test call myself using CsipSimple to 1235@always-on and I can see that CsipSimple picks the proper ip address for Contact header and also that BYE arrives at CsipSimple.
CsipSimple is using the pjsip NAT library http://www.pjsip.org/docs/latest/pjnath/docs/html/index.htm for NAT discovery etc, maybe you can check for hints there.

The Via header will be used for responses and not for sub-sequent requests such as BYE.

I think we should stick to the specs and maybe you should consider implementing STUN earlier in the roadmap or push mobile network later in the roadmap.

**Comment by atsakiridis** [comment]
We'll address this by properly implementing STUN with #177. Meanwhile, we will investigate if we can adapt Restcomm to work in those scenarios
