### ISSUE TITLE
Add DTMF support

### ISSUE THREAD

**Issue by mehturt** [Mobicents/restcomm-android-sdk#19]
Would it be possible to add DTMF support? I need this for my application :) I'll be willing to spend some time on this, if someone can give me directions..

**Comment by ivelin** [comment]
Yes. We support both RTP inband and out of band DTMF generation at the Media Server. 

The code can be adapted for the android client.

**Comment by mehturt** [comment]
By  Media Server you mean https://github.com/Mobicents/mediaserver ? Thanks.

**Comment by atsakiridis** [comment]
Correct :)
