### ISSUE TITLE
Sdk Not Working. No Libs 

### ISSUE THREAD

**Issue by JohnforDoe** [Mobicents/restcomm-android-sdk#203]
nothing in this repo seems to be working.
first of all. where are the webrtc libs that work with the sdk ? 
second, even the jain sip example crashes when you press the call button. 
this is the error 
```
0-10 15:36:14.866  25465-25774/com.example.sipmessagetest E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-33643
    Process: com.example.sipmessagetest, PID: 25465
    java.lang.NullPointerException: Attempt to invoke interface method 'android.javax.sip.ClientTransaction android.javax.sip.SipProvider.getNewClientTransaction(android.javax.sip.message.Request)' on a null object reference
            at org.mobicents.restcomm.android.sipua.impl.SipManager$5.run(SipManager.java:453)
```

**Comment by atsakiridis** [comment]
@JohnforDoe, we avoid uploading such big libs in version control, as they make it huge. You can find them in the release section of GitHub.

Regarding jain sip example. It has been obsoleted by Messenger example that uses, the newer, high level API (i.e. RestComm Client SDK).

Here's a quick start guide for the SDK, to get you up to speed:

http://docs.telestax.com/restcomm-client-android-sdk-quick-start/

Let me know if you find other issues
