### ISSUE TITLE
Use registrarless by default and fix default contact list accordingly

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#253]
Impacts:
- use registrarless so that devs can check cloud out (without having a user registered), this will also make it easier for us (we avoid having to fix the user before we can use cloud). This means update hello world and olympus apps to use empty domain by default
- remove alice & bob from default contact list (since they won't be working by default when in registrarless mode)
- add some numbers that are missing from the contact list like 1236, 1310
- update domain from 'telestax.com' to 'cloud.restcomm.com'

**Comment by deruelle** [comment]
Agreed.

**Comment by atsakiridis** [comment]
Not sure how but this commit got messed up somehow will recommit
