### ISSUE TITLE
Null pointer Exception at DeviceImpl.GetInstance().Call in new uploaded sdk

### ISSUE THREAD

**Issue by pankajsewalia01** [Mobicents/restcomm-android-sdk#33]
i am upgrading previous Sdk with new one,  Null pointer Exception at DeviceImpl.GetInstance().Call in new uploaded sdk
java.lang.NullPointerException
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2343)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at android.app.ActivityThread.access$600(ActivityThread.java:162)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at android.os.Looper.loop(Looper.java:194)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at android.app.ActivityThread.main(ActivityThread.java:5371)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at java.lang.reflect.Method.invoke(Method.java:525)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at dalvik.system.NativeStart.main(Native Method)
06-18 21:37:48.052: E/AndroidRuntime(11588): Caused by: java.lang.NullPointerException
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at com.android.internal.os.LoggingPrintStream.println(LoggingPrintStream.java:298)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at org.mobicents.restcomm.android.sipua.impl.sipmessages.Invite.MakeRequest(Invite.java:129)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at org.mobicents.restcomm.android.sipua.impl.SipManager.Call(SipManager.java:735)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at org.mobicents.restcomm.android.sipua.impl.DeviceImpl.Call(DeviceImpl.java:183)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at me.cs.oicalls.CallOut.onCreate(CallOut.java:78)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at android.app.Activity.performCreate(Activity.java:5122)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1084)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
06-18 21:37:48.052: E/AndroidRuntime(11588): 	... 11 more

**Comment by pankajsewalia01** [comment]
solved but Hangup() doesnot working

**Comment by atsakiridis** [comment]
@pankajsewalia01 Did you get the exception using the JAIN SIP sample project? Cause I tried it yesterday and had no issues. How was it solved? Do you think you can provide a network capture with the failing Hangup to have a look? Console logs would be nice too :)

Thanks

**Comment by pankajsewalia01** [comment]
i just solved it by adding customHeader HashMap to
DeviceImpl.GetInstance().Initialize(getApplicationContext(),
sipProfile,customHeaders);
